### PR TITLE
fix #300 and #280

### LINKED ISSUE #300: 0.28.0 broke fabric version listing
Commit Voxelum/x-minecraft-launcher@96fa268 which was included in the [`v0.28.0`](https://github.com/Voxelum/x-minecraft-launcher/releases/tag/v0.28.0) release broke fabric version listing by adding an extra `/v2` to the request path for both the fabric yarn and loader versions list requests which causes the fabric meta api to always return a 404 error as that path does not exist. (ex. `https://meta.fabricmc.net/v2/v2/versions/loader`)

https://github.com/Voxelum/x-minecraft-launcher/blob/c383744a75b3bcc06b1707fcd4e0aef4f245f416/xmcl-runtime/lib/services/InstallService.ts#L168
https://github.com/Voxelum/x-minecraft-launcher/blob/96fa2686a07f8f11e91ef74e24773cbdbc03e382/xmcl-runtime/lib/services/InstallService.ts#L183

**To Reproduce**

1. Go to 'Profiles'
2. Click on a profile
3. Click 'Versions'
4. Switch to the 'Fabric' tab.
5. 'No Fabric Version for Minecraft...'

**Expected behavior**
A list of installable fabric versions for the profiles selected Minecraft version

**Environment**
 - OS: Windows 10
 - Version 0.28.1

### PR DESCRIPTION
**Pull request by trbodev**

### CODE REVIEW

File: xmcl-runtime/lib/services/InstallService.ts [hunk 1]
```diff
@@ -165,7 +165,7 @@ export class InstallService extends AbstractService implements IInstallService {
       fabricMetaUrl = this.baseService.getApiSets()[0].url + '/fabric-meta'
     }
 
-    const response = await this.networkManager.request.get(`${fabricMetaUrl}/v2/versions/yarn`, {
```
Comment (ci010) [inline xmcl-runtime/lib/services/InstallService.ts:168]: Sorry about this stupid error. I forgot to test the official api.

Can you change the line 163 

```ts
let fabricMetaUrl = DEFAULT_FABRIC_API
```

to

```ts
    let fabricMetaUrl = 'https://meta.fabricmc.net'
```
Otherwise it will break the BMCL api cases...

**Review by ci010 — CHANGES_REQUESTED** [review]

File: xmcl-runtime/lib/services/InstallService.ts (hunk 1 above)
Comment (trbodev) [reply xmcl-runtime/lib/services/InstallService.ts:168]: ah, thanks for the heads up, will change

**Review by ci010 — APPROVED** [review]
